#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"DCOffsetter.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"DCOffsetter VST3 (64Bit)"
#else
#define stringFileDescription	"DCOffsetter VST3"
#endif
#define stringCompanyName		"Jonas M\0"
#define stringLegalCopyright	"Copyright(c) 2023 Jonas M."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
